version: "2"

run:
  timeout: 5m

issue:
  new: true

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - err113
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wsl
    - wrapcheck
    - interfacebloat
    - maintidx
    - nilnil
    - perfsprint
    - gomoddirectives
    - errcheck

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    goconst:
      min-occurrences: 4
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    misspell:
      locale: US

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
